### ISSUE TITLE
题目中嵌着图片的（比如公式）题目的模型设计问题

### ISSUE THREAD

**Issue by rankun203** [rankun203/OnlineTeach#3]
我想了一个方法：用一个#!img!#占位符占位，然后给每种fullTopic题目添加一个addImg的方法，img的顺序依照#!img!#占位符的顺序来。
<br>img可以是一个单独的类，从UpFile继承，但又觉得直接在UpFile里面加一个type字段要好些呢。肿么办。。

**Comment by chenjian994** [comment]
这个随你选择，如果是继承的话，可能就表现出这种题型与其他题型的区别，如果是直接加字段，区别就不明显，当然些继承会麻烦点，加字段简单些。
